[package]
name = "wild-macho"
description = "Mach-O linking support for the Wild linker"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
derive_more.workspace = true
itertools.workspace = true
linker-utils = { path = "../linker-utils", version = "0.10.0" }
object = { workspace = true, features = ["write_std"] }
perfetto-recorder.workspace = true
rayon.workspace = true
serde.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tracing.workspace = true
wild-args = { path = "../wild-args", version = "0.10.0" }
wild-error = { path = "../wild-error", version = "0.10.0" }
wild-fs = { path = "../wild-fs", version = "0.10.0" }
wild-layout = { path = "../wild-layout", version = "0.10.0" }
wild-platform = { path = "../wild-platform", version = "0.10.0" }
wild-scripts = { path = "../wild-scripts", version = "0.10.0" }
wild-util = { path = "../wild-util", version = "0.10.0" }
zerocopy.workspace = true

[lints]
workspace = true
